export const testData = [
  {
    name: "Chloe Nosko",
    linkedinURL: "http://www.linkedin.com/in/chloenosko",
    email: "cnosko@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Tamil Arasan",
    linkedinURL: "http://www.linkedin.com/in/tamil-arasan-50a30923",
    email: "tamil.b@two95intl.com",
    companyId: "54a11e8169702da4258a6a01",
    companyName: "TWO95 International, Inc",
    companyURL: "http://www.two95intl.com",
  },
  {
    name: "Phuoc Tran",
    linkedinURL: "http://www.linkedin.com/in/phuoc-tran-411b205",
    email: "phuoc@tv2consulting.com",
    companyId: "54a138cb69702d231ff61c00",
    companyName: "TV2 Consulting",
    companyURL: "http://www.tv2consulting.com",
  },
  {
    name: "Andrea Barro",
    linkedinURL: "http://www.linkedin.com/in/andrea-barro",
    email: "andrea@tv2consulting.com",
    companyId: "54a138cb69702d231ff61c00",
    companyName: "TV2 Consulting",
    companyURL: "http://www.tv2consulting.com",
  },
  {
    name: "San Kumar",
    linkedinURL: "http://www.linkedin.com/in/san-kumar-127436b2",
    email: null,
    companyId: "54a11e8169702da4258a6a01",
    companyName: "TWO95 International, Inc",
    companyURL: "http://www.two95intl.com",
  },
  {
    name: "Anna Jones",
    linkedinURL: "http://www.linkedin.com/in/anna-jones-90029331",
    email: null,
    companyId: "54a11e8169702da4258a6a01",
    companyName: "TWO95 International, Inc",
    companyURL: "http://www.two95intl.com",
  },
  {
    name: "Andy Nelson",
    linkedinURL: "http://www.linkedin.com/in/andy-nelson-97108990",
    email: null,
    companyId: "54a11e8169702da4258a6a01",
    companyName: "TWO95 International, Inc",
    companyURL: "http://www.two95intl.com",
  },
  {
    name: "Jonas Rasmussen",
    linkedinURL: "http://www.linkedin.com/in/jonas-rasmussen-297a18b9",
    email: "jra@specialisterne.com",
    companyId: "55edb86cf3e5bb33a00037dd",
    companyName: "Specialisterne Danmark",
    companyURL: "http://www.specialisterne.com",
  },
  {
    name: "Joe Sanchez",
    linkedinURL: "http://www.linkedin.com/in/jsanchez013",
    email: "jsanchez@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Elizabeth Macdougall",
    linkedinURL: "http://www.linkedin.com/in/elizabethmacdougall",
    email: "emacdougall@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Jasdeep Kaur",
    linkedinURL: "http://www.linkedin.com/in/jasdeep-kaur-83b087221",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Santhosh Sampath",
    linkedinURL: "http://www.linkedin.com/in/santhosh-sampath-58145418b",
    email: "santhosh.sampath@two95intl.com",
    companyId: "54a11e8169702da4258a6a01",
    companyName: "TWO95 International, Inc",
    companyURL: "http://www.two95intl.com",
  },
  {
    name: "Shea Cole",
    linkedinURL: "http://www.linkedin.com/in/sheacole",
    email: "scole@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Luke Hurlbut",
    linkedinURL: "http://www.linkedin.com/in/luke-hurlbut-4586b5222",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Zachary Sheriff",
    linkedinURL: "http://www.linkedin.com/in/zachary-sheriff-603116194",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Terry Cooke",
    linkedinURL: "http://www.linkedin.com/in/terry-cooke-9902a7133",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Andrea Klimova",
    linkedinURL: "http://www.linkedin.com/in/andrea-klimova-b8a1176b",
    email: "andrea.klimova@specialisterne.com",
    companyId: "55edb86cf3e5bb33a00037dd",
    companyName: "Specialisterne Danmark",
    companyURL: "http://www.specialisterne.com",
  },
  {
    name: "Johnnie Kragh",
    linkedinURL: "http://www.linkedin.com/in/johnnie-kragh-27a7733a",
    email: null,
    companyId: "55edb86cf3e5bb33a00037dd",
    companyName: "Specialisterne Danmark",
    companyURL: "http://www.specialisterne.com",
  },
  {
    name: "Yuvraj Gandhi",
    linkedinURL: "http://www.linkedin.com/in/yuvraj-gandhi-0604ab1a2",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Catherine Cuison",
    linkedinURL: "http://www.linkedin.com/in/catherine-cuison-293bb7126",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Malcolm Argyle",
    linkedinURL: "http://www.linkedin.com/in/malcolm-argyle-b799a73a",
    email: "argyle@sgl.com",
    companyId: "54a129ae69702dc128af7d01",
    companyName: "Sander Geophysics",
    companyURL: "http://www.sgl.com",
  },
  {
    name: "Rob Sloan",
    linkedinURL: "http://www.linkedin.com/in/sloanrob",
    email: "rsloan@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Daniel Keyes",
    linkedinURL: "http://www.linkedin.com/in/daniel-keyes",
    email: "daniel@pinax.network",
    companyId: "62a330936d836000dfaaf50c",
    companyName: "Pinax",
    companyURL: "http://www.pinax.network",
  },
  {
    name: "Andrew Loschmann",
    linkedinURL: "http://www.linkedin.com/in/andrew-loschmann-80ba78116",
    email: "aloschmann@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Carsten Lassen",
    linkedinURL: "http://www.linkedin.com/in/carsten-lassen-9b29832",
    email: "car@specialisterne.com",
    companyId: "55edb86cf3e5bb33a00037dd",
    companyName: "Specialisterne Danmark",
    companyURL: "http://www.specialisterne.com",
  },
  {
    name: "Nipun Malik",
    linkedinURL: "http://www.linkedin.com/in/nipun-malik-76ba92192",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Vaibhav Malik",
    linkedinURL: "http://www.linkedin.com/in/vaibhav-malik-2302b4137",
    email: null,
    companyId: "5a9ee26ba6da98d932e63b09",
    companyName: "FRESHCO, LTD.",
    companyURL: "http://www.freshco.com",
  },
  {
    name: "Matthew Holland",
    linkedinURL: "http://www.linkedin.com/in/matthewhollandfes",
    email: "mholland@fieldeffect.com",
    companyId: "5a9dbe34a6da98d932e20d50",
    companyName: "Field Effect",
    companyURL: "http://www.fieldeffect.com",
  },
  {
    name: "Chi Wong",
    linkedinURL: "http://www.linkedin.com/in/chi-wong-ba9176",
    email: "chi@tv2consulting.com",
    companyId: "54a138cb69702d231ff61c00",
    companyName: "TV2 Consulting",
    companyURL: "http://www.tv2consulting.com",
  },
  {
    name: "Denis Carriere",
    linkedinURL: "http://www.linkedin.com/in/deniscarriere",
    email: "denis@pinax.network",
    companyId: "62a330936d836000dfaaf50c",
    companyName: "Pinax",
    companyURL: "http://www.pinax.network",
  },
];
